# Make sure we’re using the latest Homebrew
update

# And have upgraded packages [optional]
upgrade

# Useful baseline of packages
install autoconf
install automake
install libffi
install libyaml
install openssl
install qt
install readline

# All the other "standard" packages
install ag
install aget
install chruby
install coreutils
install dnstop
install dos2unix
install exiftool
install ffmpeg
install freeimage
install freetype
install gist
install git
install git-extras
install gnu-sed
install gnu-time
install gnupg
install gnutls
install gpgme
install htop-osx
install hub
install imagemagick
install ioping
install jq
install lynx
install md5sha1sum
install mplayer
install mtr
install netcat
install ngrep
install phantomjs
install pkg-config
install proctools
install psgrep
install pwgen
install python --with-brewed-openssl
install python3 --with-brewed-openssl
install redis
install rtmpdump
install ruby-install
install sqlite
install tree
install unrar
install watch
install wdiff
install wget
install wkhtmltopdf
install youtube-dl

# Things not in main repo
tap homebrew/dupes
install apple-gcc42

# Percona server install
tap homebrew/versions
install percona-server55

# Brew cask!
tap phinze/cask
install brew-cask

# Install some apps
cask install betterzipql
cask install bonjour-browser
cask install charles
cask install coconutbattery
cask install dropbox
cask install evernote
cask install f-lux
cask install firefox
cask install gfxcardstatus
cask install gitx
cask install google-chrome
cask install httpscoop
cask install launchbar
cask install limechat
cask install mplayerx
cask install picturelife
cask install qlcolorcode
cask install qlmarkdown
cask install qlprettypatch
cask install qlstephen
cask install quicklook-csv
cask install quicklook-json
cask install scriptql
cask install skype
cask install spotify
cask install suspicious-package
cask install textwrangler
cask install the-unarchiver
cask install virtualbox
cask install vagrant
cask install viscosity
cask install webp-quicklook

# Install some fonts
tap caskroom/fonts
cask install font-inconsolata
cask install font-liberation-sans
cask install font-open-sans
cask install font-source-code-pro
cask install font-source-sans-pro

# Remove outdated versions from the cellar
cleanup
