#!/usr/bin/env zsh
# Symlinks ~/.zsh/dotfiles/* to ~/.* (or ~/* - see $NO_DOT)
# Moves existing files aside if they don't match, to ~/.*.EPOCH-old

set -e

ZSH_ROOT="$HOME/.zsh"
NO_DOT=(Brewfile)

git submodule update --init

echo "Installing dotfiles from $ZSH_ROOT/dotfiles to $HOME"

echo -n ".bundle/config"
if [[ ! -f "$HOME/.bundle/config" ]]; then
  echo -n " ..installing link"
  mkdir -p "$HOME/.bundle"
  ln -s "$ZSH_ROOT/dotfiles/.bundle/config" "$HOME/.bundle/config"
fi
echo " ..done!"

# for DIR in $(find $ZSH_ROOT/dotfiles/ -type d -depth 1); do
#   DEST="$HOME/$(basename $DIR)"
#   if [[ ! -d $DEST ]]; then
#     echo "Creating $DEST"
#     mkdir -p $DEST
#   fi
# done

for FROM in $ZSH_ROOT/dotfiles/*; do
  NAME="$(basename $FROM)"

  # Dot the file unless it's blacklisted
  if [[ ! -n ${(M)NO_DOT:#${NAME}} ]]; then
    NAME=".${NAME}"
  fi

  TO="$HOME/$NAME"
  # echo "TO: $TO"
  # echo "FROM: $FROM"

  echo -n "$NAME"

  # See if it exists
  if [[ -f $TO ]]; then
    # See if it matches what we're about to install
    if [[ "$(md5 -q $TO)" == "$(md5 -q $FROM)" ]]; then
      # If so, we're done here for this file
      echo "  ..done!"
      continue
    else
      # Need to backup the existing one
      echo -n "  ..moving existing"
      mv "$TO" "$TO.$(date '+%s')-old"
    fi
  fi

  echo -n "  ..installing link"
  ln -s $FROM $TO
  echo "  ..done!"

done

echo "Installing binfiles to ~/bin"

(cd vendor/Binfiles && rake)

echo "All installed!"
